apiVersion: apps/v1
kind: Deployment
metadata:
  name: openrmf-compliance
  namespace: {{.Values.namespace}}
  labels:
    app.kubernetes.io/name: openrmf
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/component: compliance-api
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/revision: "{{ .Release.Revision }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: helm
spec:
  selector:
    matchLabels:
      run: openrmf-compliance
  replicas: 1
  template:
    metadata:
      labels:
        run: openrmf-compliance
    spec:
      containers:
      - name: openrmf-compliance
        image: cingulara/openrmf-api-compliance:{{.Values.complianceImage}}
        ports:
        - name: web-port
          containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: web-port
          initialDelaySeconds: 5
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /healthz
            port: web-port
          initialDelaySeconds: 3
          periodSeconds: 30
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ASPNETCORE_URLS
          value: http://*:8080
        - name: NATSSERVERURL
          value: nats://natsserver:4222
        - name: JWT-AUTHORITY
          value: {{.Values.identityProviderURL}}/realms/{{.Values.identityProviderRealm}}
        - name: JWT-CLIENT
          value: {{.Values.identityProviderClientId}}
        resources:
          limits:
            memory: "750Mi"
            cpu: "500m"
          requests:
            memory: "250Mi"
            cpu: "100m"
{{/* Use this service definition and NGINX controller setup if minikube */}}
{{ if and .Values.installType (eq .Values.installType "minikube") }}
---
apiVersion: v1
kind: Service
metadata:
  name: openrmf-compliance
  namespace: {{.Values.namespace}}
  labels:
    app.kubernetes.io/name: openrmf
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/component: compliance-api
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/revision: "{{ .Release.Revision }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: helm
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: openrmf-compliance
  sessionAffinity: None
  type: {{.Values.serviceType}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openrmf-compliance-ingress
  namespace: {{.Values.namespace}}
  labels:
    app.kubernetes.io/name: openrmf
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/component: compliance-api-ingress
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/revision: "{{ .Release.Revision }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: helm
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, OPTIONS"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: 5m
spec:
  rules:
  - host: {{.Values.dnsName}}
    http:
      paths:
      - path: /api/compliance(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: openrmf-compliance
            port:
              number: 8080
{{ end }}
{{/* Use this service definition and Load Balancer type setup if AWS EKS */}}
{{ if and .Values.installType (eq .Values.installType "awseks") }}
---
apiVersion: v1
kind: Service
metadata:
  name: openrmf-compliance
  namespace: {{.Values.namespace}}
  labels:
    app.kubernetes.io/name: openrmf
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/component: compliance-api
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/revision: "{{ .Release.Revision }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: helm
  annotations:
    # Note that the backend talks over HTTP.
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    # The ARN of your certificate.
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{.Values.awsACM}}
    # Only run SSL on the port named "https" below.
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    run: openrmf-compliance
  sessionAffinity: None
  type: {{.Values.serviceTypeAWS | default "LoadBalancer"}}
{{ end }}
{{ if .Values.useprometheusoperator }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: openrmf-compliance-api-metrics
  namespace: {{.Values.namespace}}
  labels:
    app.kubernetes.io/name: openrmf
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/component: compliance-api
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/revision: "{{ .Release.Revision }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: helm
    {{ .Values.servicemonitormatchlabelname }}: {{ .Values.servicemonitormatchlabelvalue }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: compliance-api
  endpoints:
  - port: https
    interval: 15s
    path: /metrics
  namespaceSelector:
    matchNames:
    - {{.Values.namespace}}
{{ end }}
