apiVersion: v1
items:
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: "2020-04-07T20:52:50Z"
    generation: 1
    labels:
      app: prometheus-operator-alertmanager
      chart: prometheus-operator-8.12.8
      heritage: Helm
      release: prometheus-operator-1586292731
    name: prometheus-operator-158629-alertmanager
    namespace: default
    resourceVersion: "24085403"
    selfLink: /apis/monitoring.coreos.com/v1/namespaces/default/servicemonitors/prometheus-operator-158629-alertmanager
    uid: 7b45a277-2324-428b-97f0-8eb48946ccb4
  spec:
    endpoints:
    - path: /metrics
      port: web
    namespaceSelector:
      matchNames:
      - default
    selector:
      matchLabels:
        app: prometheus-operator-alertmanager
        release: prometheus-operator-1586292731
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: "2020-04-07T20:52:50Z"
    generation: 1
    labels:
      app: prometheus-operator-apiserver
      chart: prometheus-operator-8.12.8
      heritage: Helm
      release: prometheus-operator-1586292731
    name: prometheus-operator-158629-apiserver
    namespace: default
    resourceVersion: "24085407"
    selfLink: /apis/monitoring.coreos.com/v1/namespaces/default/servicemonitors/prometheus-operator-158629-apiserver
    uid: d69fdef1-6b98-4f14-80b5-af4d19d2d3c8
  spec:
    endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      port: https
      scheme: https
      tlsConfig:
        caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecureSkipVerify: false
        serverName: kubernetes
    jobLabel: component
    namespaceSelector:
      matchNames:
      - default
    selector:
      matchLabels:
        component: apiserver
        provider: kubernetes
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: "2020-04-07T20:52:50Z"
    generation: 1
    labels:
      app: prometheus-operator-coredns
      chart: prometheus-operator-8.12.8
      heritage: Helm
      release: prometheus-operator-1586292731
    name: prometheus-operator-158629-coredns
    namespace: default
    resourceVersion: "24085405"
    selfLink: /apis/monitoring.coreos.com/v1/namespaces/default/servicemonitors/prometheus-operator-158629-coredns
    uid: a5a5fe04-9a81-4b94-8c1b-1ac83e96accc
  spec:
    endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      port: http-metrics
    jobLabel: jobLabel
    namespaceSelector:
      matchNames:
      - kube-system
    selector:
      matchLabels:
        app: prometheus-operator-coredns
        release: prometheus-operator-1586292731
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: "2020-04-07T20:52:50Z"
    generation: 1
    labels:
      app: prometheus-operator-grafana
      chart: prometheus-operator-8.12.8
      heritage: Helm
      release: prometheus-operator-1586292731
    name: prometheus-operator-158629-grafana
    namespace: default
    resourceVersion: "24085412"
    selfLink: /apis/monitoring.coreos.com/v1/namespaces/default/servicemonitors/prometheus-operator-158629-grafana
    uid: bb739743-9065-4822-abfa-33c0b05c0148
  spec:
    endpoints:
    - path: /metrics
      port: service
    namespaceSelector:
      matchNames:
      - default
    selector:
      matchLabels:
        app.kubernetes.io/instance: prometheus-operator-1586292731
        app.kubernetes.io/name: grafana
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: "2020-04-07T20:52:50Z"
    generation: 1
    labels:
      app: prometheus-operator-kube-controller-manager
      chart: prometheus-operator-8.12.8
      heritage: Helm
      release: prometheus-operator-1586292731
    name: prometheus-operator-158629-kube-controller-manager
    namespace: default
    resourceVersion: "24085411"
    selfLink: /apis/monitoring.coreos.com/v1/namespaces/default/servicemonitors/prometheus-operator-158629-kube-controller-manager
    uid: 0864e3f5-8a57-4b1b-b4c8-9908a685221c
  spec:
    endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      port: http-metrics
    jobLabel: jobLabel
    namespaceSelector:
      matchNames:
      - kube-system
    selector:
      matchLabels:
        app: prometheus-operator-kube-controller-manager
        release: prometheus-operator-1586292731
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: "2020-04-07T20:52:50Z"
    generation: 1
    labels:
      app: prometheus-operator-kube-etcd
      chart: prometheus-operator-8.12.8
      heritage: Helm
      release: prometheus-operator-1586292731
    name: prometheus-operator-158629-kube-etcd
    namespace: default
    resourceVersion: "24085410"
    selfLink: /apis/monitoring.coreos.com/v1/namespaces/default/servicemonitors/prometheus-operator-158629-kube-etcd
    uid: 519520b6-0c39-4518-9f66-0911ee8e8d9b
  spec:
    endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      port: http-metrics
    jobLabel: jobLabel
    namespaceSelector:
      matchNames:
      - kube-system
    selector:
      matchLabels:
        app: prometheus-operator-kube-etcd
        release: prometheus-operator-1586292731
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: "2020-04-07T20:52:50Z"
    generation: 1
    labels:
      app: prometheus-operator-kube-proxy
      chart: prometheus-operator-8.12.8
      heritage: Helm
      release: prometheus-operator-1586292731
    name: prometheus-operator-158629-kube-proxy
    namespace: default
    resourceVersion: "24085400"
    selfLink: /apis/monitoring.coreos.com/v1/namespaces/default/servicemonitors/prometheus-operator-158629-kube-proxy
    uid: cb88f6f1-191e-452c-989c-c14038eb4afa
  spec:
    endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      port: http-metrics
    jobLabel: jobLabel
    namespaceSelector:
      matchNames:
      - kube-system
    selector:
      matchLabels:
        app: prometheus-operator-kube-proxy
        release: prometheus-operator-1586292731
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: "2020-04-07T20:52:50Z"
    generation: 1
    labels:
      app: prometheus-operator-kube-scheduler
      chart: prometheus-operator-8.12.8
      heritage: Helm
      release: prometheus-operator-1586292731
    name: prometheus-operator-158629-kube-scheduler
    namespace: default
    resourceVersion: "24085402"
    selfLink: /apis/monitoring.coreos.com/v1/namespaces/default/servicemonitors/prometheus-operator-158629-kube-scheduler
    uid: c3705102-645d-41f2-9d35-b85861ebc4c4
  spec:
    endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      port: http-metrics
    jobLabel: jobLabel
    namespaceSelector:
      matchNames:
      - kube-system
    selector:
      matchLabels:
        app: prometheus-operator-kube-scheduler
        release: prometheus-operator-1586292731
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: "2020-04-07T20:52:50Z"
    generation: 1
    labels:
      app: prometheus-operator-kube-state-metrics
      chart: prometheus-operator-8.12.8
      heritage: Helm
      release: prometheus-operator-1586292731
    name: prometheus-operator-158629-kube-state-metrics
    namespace: default
    resourceVersion: "24085406"
    selfLink: /apis/monitoring.coreos.com/v1/namespaces/default/servicemonitors/prometheus-operator-158629-kube-state-metrics
    uid: 0c887d90-d59a-412e-b19e-995360476f52
  spec:
    endpoints:
    - honorLabels: true
      port: http
    jobLabel: app.kubernetes.io/name
    selector:
      matchLabels:
        app.kubernetes.io/instance: prometheus-operator-1586292731
        app.kubernetes.io/name: kube-state-metrics
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: "2020-04-07T20:52:50Z"
    generation: 1
    labels:
      app: prometheus-operator-kubelet
      chart: prometheus-operator-8.12.8
      heritage: Helm
      release: prometheus-operator-1586292731
    name: prometheus-operator-158629-kubelet
    namespace: default
    resourceVersion: "24085409"
    selfLink: /apis/monitoring.coreos.com/v1/namespaces/default/servicemonitors/prometheus-operator-158629-kubelet
    uid: cf6cd0e1-c531-4e00-aed9-6ed25ffb6d9a
  spec:
    endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      honorLabels: true
      port: https-metrics
      relabelings:
      - sourceLabels:
        - __metrics_path__
        targetLabel: metrics_path
      scheme: https
      tlsConfig:
        caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecureSkipVerify: true
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      honorLabels: true
      path: /metrics/cadvisor
      port: https-metrics
      relabelings:
      - sourceLabels:
        - __metrics_path__
        targetLabel: metrics_path
      scheme: https
      tlsConfig:
        caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecureSkipVerify: true
    jobLabel: k8s-app
    namespaceSelector:
      matchNames:
      - kube-system
    selector:
      matchLabels:
        k8s-app: kubelet
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: "2020-04-07T20:52:50Z"
    generation: 1
    labels:
      app: prometheus-operator-node-exporter
      chart: prometheus-operator-8.12.8
      heritage: Helm
      release: prometheus-operator-1586292731
    name: prometheus-operator-158629-node-exporter
    namespace: default
    resourceVersion: "24085408"
    selfLink: /apis/monitoring.coreos.com/v1/namespaces/default/servicemonitors/prometheus-operator-158629-node-exporter
    uid: f99124c1-0d50-4d6e-a047-96164175f1d6
  spec:
    endpoints:
    - port: metrics
    jobLabel: jobLabel
    selector:
      matchLabels:
        app: prometheus-node-exporter
        release: prometheus-operator-1586292731
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: "2020-04-07T20:52:50Z"
    generation: 1
    labels:
      app: prometheus-operator-operator
      chart: prometheus-operator-8.12.8
      heritage: Helm
      release: prometheus-operator-1586292731
    name: prometheus-operator-158629-operator
    namespace: default
    resourceVersion: "24085404"
    selfLink: /apis/monitoring.coreos.com/v1/namespaces/default/servicemonitors/prometheus-operator-158629-operator
    uid: 20454e96-a23a-4e64-922f-75b123709ce4
  spec:
    endpoints:
    - honorLabels: true
      port: http
    namespaceSelector:
      matchNames:
      - default
    selector:
      matchLabels:
        app: prometheus-operator-operator
        release: prometheus-operator-1586292731
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: "2020-04-07T20:52:50Z"
    generation: 1
    labels:
      app: prometheus-operator-prometheus
      chart: prometheus-operator-8.12.8
      heritage: Helm
      release: prometheus-operator-1586292731
    name: prometheus-operator-158629-prometheus
    namespace: default
    resourceVersion: "24085401"
    selfLink: /apis/monitoring.coreos.com/v1/namespaces/default/servicemonitors/prometheus-operator-158629-prometheus
    uid: 9b609de4-630c-460e-be62-efeaef06332c
  spec:
    endpoints:
    - path: /metrics
      port: web
    namespaceSelector:
      matchNames:
      - default
    selector:
      matchLabels:
        app: prometheus-operator-prometheus
        release: prometheus-operator-1586292731
        self-monitor: "true"
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"monitoring.coreos.com/v1","kind":"ServiceMonitor","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"read-api","app.kubernetes.io/instance":"version-0.13","app.kubernetes.io/managed-by":"helm","app.kubernetes.io/name":"openrmf","app.kubernetes.io/revision":"0","app.kubernetes.io/version":"0.13","helm.sh/chart":"openrmf-1.1.0"},"name":"openrmf-read-api-metrics","namespace":"openrmf"},"spec":{"endpoints":[{"interval":"15s","port":"https"}],"namespaceSelector":{"matchNames":["openrmf"]},"selector":{"matchLabels":{"app.kubernetes.io/component":"read-api"}}}}
    creationTimestamp: "2020-04-08T10:26:37Z"
    generation: 1
    labels:
      app.kubernetes.io/component: read-api
      app.kubernetes.io/instance: version-0.13
      app.kubernetes.io/managed-by: helm
      app.kubernetes.io/name: openrmf
      app.kubernetes.io/revision: "0"
      app.kubernetes.io/version: "0.13"
      helm.sh/chart: openrmf-1.1.0
    name: openrmf-read-api-metrics
    namespace: openrmf
    resourceVersion: "24184009"
    selfLink: /apis/monitoring.coreos.com/v1/namespaces/openrmf/servicemonitors/openrmf-read-api-metrics
    uid: dc955ff6-35ec-4a8f-978c-f476f6e37cc3
  spec:
    endpoints:
    - interval: 15s
      port: https
      path: /metrics
    namespaceSelector:
      matchNames:
      - openrmf
    selector:
      matchLabels:
        app.kubernetes.io/component: read-api
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
