version : '3.8'
 
services:
### 1 Web Front End Container
  openrmf-web:
    image: cingulara/openrmf-web:1.05.04
    container_name: openrmf-web
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - openrmfapi-scoring
      - openrmfapi-save
      - openrmfapi-template
      - openrmfapi-upload
      - openrmfapi-read
      - openrmfapi-compliance
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - openrmf

### 9 API Containers
  openrmfapi-scoring:
    image: cingulara/openrmf-api-scoring:1.05.01
    container_name: openrmf-scoring-api
    restart: always
    ports:
      - 8090
    env_file: .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8090
      - DBCONNECTION=mongodb://openrmfscore:openrmf1234!@scoredb/openrmfscore?authSource=openrmfscore
      - DBTYPE=mongo
      - DB=openrmfscore
    depends_on:
      - scoredb
    networks:
      - openrmf
  
  openrmfapi-save:
    image: cingulara/openrmf-api-save:1.05.01
    container_name: openrmf-save-api
    restart: always
    ports:
      - 8082
    env_file: .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8082
      - DBCONNECTION=mongodb://openrmf:openrmf1234!@checklistdb/openrmf?authSource=openrmf
      - DB=openrmf
      - DBTYPE=mongo
      - NATSSERVERURL=nats://natsserver:4222
    depends_on:
      - openrmfmsg-score
      - checklistdb
      - natsserver
    networks:
      - openrmf

  openrmfapi-template:
    image: cingulara/openrmf-api-template:1.05.04
    container_name: openrmf-template-api
    restart: always
    ports:
      - 8088
    env_file: .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8088
      - NATSSERVERURL=nats://natsserver:4222
      - DBCONNECTION=mongodb://openrmftemplate:openrmf1234!@templatedb/openrmftemplate?authSource=openrmftemplate
      - DB=openrmftemplate
      - DBTYPE=mongo
    depends_on:
      - templatedb
    networks:
      - openrmf

  openrmfapi-upload:
    image: cingulara/openrmf-api-upload:1.05.01
    container_name: openrmf-upload-api
    restart: always
    ports:
      - 8086
    env_file: .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8086
      - DBCONNECTION=mongodb://openrmf:openrmf1234!@checklistdb/openrmf?authSource=openrmf
      - DB=openrmf
      - DBTYPE=mongo
      - NATSSERVERURL=nats://natsserver:4222
    depends_on:
      - openrmfmsg-score
      - checklistdb
      - natsserver
    networks:
      - openrmf

  openrmfapi-read:
    image: cingulara/openrmf-api-read:1.05.02
    container_name: openrmf-read-api
    restart: always
    ports:
      - 8084
    env_file: .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8084
      - DBCONNECTION=mongodb://openrmf:openrmf1234!@checklistdb/openrmf?authSource=openrmf
      - DB=openrmf
      - DBTYPE=mongo
      - NATSSERVERURL=nats://natsserver:4222
    depends_on:
      - checklistdb
    networks:
      - openrmf

  openrmfapi-compliance:
    image: cingulara/openrmf-api-compliance:1.05.01
    container_name: openrmf-compliance-api
    restart: always
    ports:
      - 8092
    env_file: .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8092
      - NATSSERVERURL=nats://natsserver:4222
    networks:
      - openrmf

  openrmfapi-controls:
    image: cingulara/openrmf-api-controls:1.05.01
    container_name: openrmf-controls-api
    restart: always
    ports:
      - 8094
    env_file: .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8094
      - NATSSERVERURL=nats://natsserver:4222
    networks:
      - openrmf

  openrmfapi-audit:
    image: cingulara/openrmf-api-audit:1.05.01
    container_name: openrmf-audit-api
    restart: always
    ports:
      - 8096
    env_file: .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8096
      - DBCONNECTION=mongodb://openrmfaudit:openrmf1234!@auditdb/openrmfaudit?authSource=openrmfaudit
      - DB=openrmfaudit
      - DBTYPE=mongo
      - NATSSERVERURL=nats://natsserver:4222
    depends_on:
      - auditdb
    networks:
      - openrmf

  openrmfapi-report:
    image: cingulara/openrmf-api-report:1.05.01
    container_name: openrmf-report-api
    restart: always
    ports:
      - 8098
    env_file: .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8098
      - DBCONNECTION=mongodb://openrmfreport:openrmf1234!@reportdb/openrmfreport?authSource=openrmfreport
      - DB=openrmfreport
      - DBTYPE=mongo
      - NATSSERVERURL=nats://natsserver:4222
    depends_on:
      - reportdb
    networks:
      - openrmf

### 8 Messaging Containers
  openrmfmsg-score:
    image: cingulara/openrmf-msg-score:1.04.00
    container_name: openrmf-score-nats-message-client
    restart: always
    environment:
      - DBCONNECTION=mongodb://openrmfscore:openrmf1234!@scoredb/openrmfscore?authSource=openrmfscore
      - DBTYPE=mongo
      - DB=openrmfscore
      - NATSSERVERURL=nats://natsserver:4222
    depends_on:
      - scoredb
      - natsserver
    networks:
      - openrmf

  openrmfmsg-checklist:
    image: cingulara/openrmf-msg-checklist:1.03.00
    container_name: openrmf-checklist-nats-message-client
    restart: always
    environment:
      - DBCONNECTION=mongodb://openrmf:openrmf1234!@checklistdb/openrmf?authSource=openrmf
      - DB=openrmf
      - DBTYPE=mongo
      - NATSSERVERURL=nats://natsserver:4222
    depends_on:
      - checklistdb
      - natsserver
    networks:
      - openrmf

  openrmfmsg-compliance:
    image: cingulara/openrmf-msg-compliance:1.03.00
    container_name: openrmf-compliance-nats-message-client
    restart: always
    environment:
      - NATSSERVERURL=nats://natsserver:4222
    depends_on:
      - natsserver
    networks:
      - openrmf

  openrmfmsg-controls:
    image: cingulara/openrmf-msg-controls:1.04.00
    container_name: openrmf-controls-nats-message-client
    restart: always
    environment:
      - NATSSERVERURL=nats://natsserver:4222
    depends_on:
      - natsserver
    networks:
      - openrmf

  openrmfmsg-template:
    image: cingulara/openrmf-msg-template:1.03.00
    container_name: openrmf-template-nats-message-client
    restart: always
    environment:
      - DBCONNECTION=mongodb://openrmftemplate:openrmf1234!@templatedb/openrmftemplate?authSource=openrmftemplate
      - DB=openrmftemplate
      - DBTYPE=mongo
      - NATSSERVERURL=nats://natsserver:4222
    depends_on:
      - templatedb
      - natsserver
    networks:
      - openrmf

  openrmfmsg-system:
    image: cingulara/openrmf-msg-system:1.03.00
    container_name: openrmf-system-nats-message-client
    restart: always
    environment:
      - DBCONNECTION=mongodb://openrmf:openrmf1234!@checklistdb/openrmf?authSource=openrmf
      - DB=openrmf
      - DBTYPE=mongo
      - NATSSERVERURL=nats://natsserver:4222
    depends_on:
      - checklistdb
      - natsserver
    networks:
      - openrmf

  openrmfmsg-audit:
    image: cingulara/openrmf-msg-audit:1.03.00
    container_name: openrmf-audit-nats-message-client
    restart: always
    environment:
      - DBCONNECTION=mongodb://openrmfaudit:openrmf1234!@auditdb/openrmfaudit?authSource=openrmfaudit
      - DB=openrmfaudit
      - DBTYPE=mongo
      - NATSSERVERURL=nats://natsserver:4222
    depends_on:
      - auditdb
      - natsserver
    networks:
      - openrmf

  openrmfmsg-reports:
    image: cingulara/openrmf-msg-reports:1.03.01
    container_name: openrmf-report-nats-message-client
    restart: always
    environment:
      - SYSTEMDBCONNECTION=mongodb://openrmf:openrmf1234!@checklistdb/openrmf?authSource=openrmf
      - SYSTEMDB=openrmf
      - SYSTEMDBTYPE=mongo
      - REPORTDBCONNECTION=mongodb://openrmfreport:openrmf1234!@reportdb/openrmfreport?authSource=openrmfreport
      - REPORTDB=openrmfreport
      - REPORTDBTYPE=mongo
      - NATSSERVERURL=nats://natsserver:4222
    depends_on:
      - checklistdb
      - reportdb
      - natsserver
    networks:
      - openrmf

### 5 MongoDB Containers
  checklistdb:
    image: cingulara/mongo:4.4.4-nonroot
    container_name: mongodb-checklist
    restart: always
    ports:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=myp2ssw0rd
      - MONGO_INITDB_DATABASE=openrmf
    volumes:
      - checklist-data-volume:/data/db
      - ./initializeChecklist.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - openrmf

  scoredb:
    image: cingulara/mongo:4.4.4-nonroot
    container_name: mongodb-score
    restart: always
    ports:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=myp2ssw0rd
      - MONGO_INITDB_DATABASE=openrmfscore
    volumes:
      - score-data-volume:/data/db
      - ./initializeScore.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - openrmf

  templatedb:
    image: cingulara/mongo:4.4.4-nonroot
    container_name: mongodb-template
    restart: always
    ports:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=myp2ssw0rd
      - MONGO_INITDB_DATABASE=openrmftemplate
    volumes:
      - template-data-volume:/data/db
      - ./initializeTemplate.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - openrmf

  auditdb:
    image: cingulara/mongo:4.4.4-nonroot
    container_name: mongodb-audit
    restart: always
    ports:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=myp2ssw0rd
      - MONGO_INITDB_DATABASE=openrmfaudit
    volumes:
      - audit-data-volume:/data/db
      - ./initializeAudit.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - openrmf

  reportdb:
    image: cingulara/mongo:4.4.4-nonroot
    container_name: mongodb-report
    restart: always
    ports:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=myp2ssw0rd
      - MONGO_INITDB_DATABASE=openrmfreport
    volumes:
      - report-data-volume:/data/db
      - ./initializeReport.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - openrmf

### NATS messaging container (internal)
  natsserver: 
    image: nats:2.1.9
    container_name: nats
    command: -m 8222
    restart: always
    ports:
      - 4222
      - 6222
      - 8222
    networks:
      - openrmf

### Metrics
  natspromexporter: 
    image: synadia/prometheus-nats-exporter:0.6.2
    container_name: nats-prometheus-exporter
    command: -varz -connz -subz http://natsserver:8222
    restart: always
    ports:
      - 7777
    networks:
      - openrmf

  nats-client-metrics: 
    image: cingulara/nats-client-metrics:1.0.1
    container_name: nats-client-metrics
    restart: always
    ports:
      - 7778
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:7778
      - NATSMETRICSURL=http://natsserver:8222
    networks:
      - openrmf

  prometheus:
    image: prom/prometheus:v2.25.0
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    restart: always
    ports:
      - 9090
    volumes:
      - openrmf-prometheus-data-volume:/prometheus # persist the data
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - openrmf

  grafana: 
    image: grafana/grafana:7.4.2
    container_name: grafana
    #command:
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=1qaz2WSX3edc4RFVgr@fana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - openrmf-grafana-data-volume:/var/lib/grafana # persist the data
      - ./grafana/dashboards/:/etc/grafana/provisioning/dashboards/:ro
      - ./grafana/datasources/:/etc/grafana/provisioning/datasources/:ro
    networks:
      - openrmf

### put all the volume listings here for persistent data
volumes:
  template-data-volume:
  checklist-data-volume:
  score-data-volume:
  audit-data-volume:
  report-data-volume:
  openrmf-prometheus-data-volume:
  openrmf-grafana-data-volume:

### put all the networks here
networks:
  openrmf:
